"use client";

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { AlertTriangle, Database } from "lucide-react";

export function DatabaseSetupGuide() {
  const sqlScript = `
-- Create the dart_scores table
CREATE TABLE IF NOT EXISTS dart_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  player TEXT NOT NULL CHECK (player IN ('robot', 'human')),
  score INTEGER NOT NULL,
  round INTEGER NOT NULL
);

-- Enable row-level security
ALTER TABLE dart_scores ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to read scores
CREATE POLICY "Anyone can read dart_scores"
  ON dart_scores
  FOR SELECT
  TO anon
  USING (true);

-- Create a policy that allows authenticated users to insert scores
CREATE POLICY "Authenticated users can insert dart_scores"
  ON dart_scores
  FOR INSERT
  TO anon
  USING (true);

-- Set up realtime publication
DROP PUBLICATION IF EXISTS supabase_realtime;
CREATE PUBLICATION supabase_realtime FOR TABLE dart_scores;
`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlScript.trim());
  };

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Database className="h-6 w-6" />
          Database Setup Required
        </CardTitle>
        <CardDescription>
          The dart_scores table doesn't exist yet. Follow these steps to set up
          your database.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <Alert variant="default">
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>Missing Database Table</AlertTitle>
          <AlertDescription>
            The application requires a "dart_scores" table in your Supabase
            database.
          </AlertDescription>
        </Alert>

        <div className="space-y-4">
          <h3 className="text-lg font-medium">Setup Instructions:</h3>
          <ol className="list-decimal space-y-2 pl-5">
            <li>Go to your Supabase dashboard</li>
            <li>Navigate to the SQL Editor</li>
            <li>Create a new query</li>
            <li>Copy and paste the SQL below</li>
            <li>Run the query</li>
            <li>Return to this page and refresh</li>
          </ol>
        </div>

        <div className="relative">
          <pre className="bg-muted overflow-x-auto rounded-md p-4 text-sm">
            <code>{sqlScript}</code>
          </pre>
          <Button
            size="sm"
            variant="secondary"
            className="absolute top-2 right-2"
            onClick={copyToClipboard}
          >
            Copy
          </Button>
        </div>
      </CardContent>
      <CardFooter>
        <p className="text-muted-foreground text-sm">
          After running the SQL script, refresh this page to see the scoreboard.
        </p>
      </CardFooter>
    </Card>
  );
}
